language: node_js
node_js: stable
sudo: false

git:
  submodules: false

script:
  - npm run test-browser

addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test

matrix:
  include:
    - script: '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || (npm run pretest && npm run test-browser)'
      env: TEST_SUITE=browser
      addons:
        sauce_connect:
          username: "jsdom"
          access_key: "7d402b1d-0388-467c-8d99-edf195456eee"
